package com.gh0u1l5.wechatmagician.spellbook.mirror

/**
 * Dynamically generated by build.gradle
 */
val MirrorClasses = listOf (
        com.gh0u1l5.wechatmagician.spellbook.mirror.android.support.v4.app.Classes,
        com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mars.xlog.Classes,
        com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.Classes,
        com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.booter.notification.Classes,
        com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.booter.notification.queue.Classes,
        com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.modelsfs.Classes,
        com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.plugin.base.stub.Classes,
        com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.plugin.gallery.ui.Classes,
        com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.plugin.remittance.ui.Classes,
        com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.plugin.sns.ui.Classes,
        com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.plugin.webwx.ui.Classes,
        com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.sdk.platformtools.Classes,
        com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.storage.Classes,
        com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.ui.Classes,
        com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.ui.base.Classes,
        com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.ui.chatting.Classes,
        com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.ui.contact.Classes,
        com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.ui.conversation.Classes,
        com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.ui.tools.Classes,
        com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.ui.transmit.Classes,
        com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.wcdb.Classes,
        com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.wcdb.database.Classes,
        com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.wcdb.support.Classes
)
