package com.gh0u1l5.wechatmagician.spellbook.mirror

/**
 * Dynamically generated by build.gradle
 */
val MirrorFields = listOf (
        com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.Fields,
        com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.plugin.sns.ui.Fields
)
