package com.gh0u1l5.wechatmagician.spellbook.mirror

/**
 * Dynamically generated by build.gradle
 */
val MirrorMethods = listOf (
        com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mars.xlog.Methods,
        com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.Methods,
        com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.booter.notification.queue.Methods,
        com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.modelsfs.Methods,
        com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.plugin.base.stub.Methods,
        com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.sdk.platformtools.Methods,
        com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.storage.Methods,
        com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.ui.Methods,
        com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.ui.transmit.Methods
)
